spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB.HOST}:${DB.PORT}/${DB.NAME}
    username: ${DB.USER}
    password: ${DB.PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS.HOST}
      port: ${REDIS.PORT}
      password: ${REDIS.USER}

jwt:
  activeKey: key1
  secretKeys:
    key1: ${KEY_1}
    key2: ${KEY_2}
    key3: ${KEY_3}